### ISSUE TITLE
Doc should link to existing integrations

### ISSUE THREAD

**Issue by mickaelistria** [LucasBullen/Project-Provisioning-Protocol#5]
I've seen several demos of 2 clients (Eclipse IDE, CLI) and 3 provisioners (cargo, webcomponents, launch.openshift.io).
It seems important to list those existing integration on a document inside the repo.
I suggest we rename the README.md to protocol.md, create an integrations.md and have the README.md explaining the goal of the PPP and linking to documentations and integrations.md.

**Comment by LucasBullen** [comment]
https://github.com/LucasBullen/ppp-examples
Will update these docs today.

**Comment by mickaelistria** [comment]
Great, thanks!
